### ISSUE TITLE
Community Modules

### ISSUE THREAD

**Issue by facekapow** [runtimejs/discussions#3]
Should there be a section in the Wiki for community modules? And maybe a link to it in the README?

**Comment by iefserge** [comment]
Yep, great idea :+1:

**Comment by facekapow** [comment]
Should modules be included even if they support runtime but aren't specifically made for runtime? Like your `eshttp` module?

**Comment by iefserge** [comment]
@facekapow I think it's fine to include those too. 
Though in case of `eshttp` we would probably need to add it to dependencies to support Node `require('http')` out of the box.

**Comment by facekapow** [comment]
@iefserge Do you have editing restricted to collaborators only? Just checking.

**Comment by iefserge** [comment]
@facekapow don't think so

**Comment by facekapow** [comment]
Forgot to close this, oops
